//! Engineering-ground distillation.
//!
//! Renders the authored engineering governance statements into one derived
//! foundational prompt source. The output is `generated-derived`: it is
//! machine-writable, re-derivable, and carries pinned provenance refs to the
//! statements it was rendered from. Human adoption promotes it; editing happens
//! at the statement layer, never on the distillate.

use crate::action::{
    ActionAvailability, ActionDescriptor, ActionExecutionContext, ActionOutputDefinition,
    ActionRegistry, MutationClass,
};
use crate::result::{ActionResult, ResultStatus};
use crate::root::resolve_central_root;
use crate::source_horizon::{
    content_revision, source_ref, SourceRevision, CONTROL_WORLD_REF,
};
use serde::Serialize;
use serde_json::Value;
use std::fs;
use std::io;
use std::path::Path;

pub const ENGINEERING_GROUND_DIR: &str = "Control/agents/governance/engineering";
pub const ENGINEERING_GROUND_STATEMENTS: [&str; 4] = [
    "agent-operations.md",
    "coding-approach.md",
    "verification.md",
    "base-skillset.md",
];
pub const ENGINEERING_GROUND_OUTPUT: &str =
    "Control/agents/governance/engineering/foundational-prompt.md";

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct EngineeringGroundRender {
    pub output_path: String,
    pub changed: bool,
    pub revision: SourceRevision,
}

fn statement_section(central_root: &Path, file: &str) -> io::Result<Option<(String, String, String)>> {
    let path = central_root.join(ENGINEERING_GROUND_DIR).join(file);
    if !path.is_file() {
        return Ok(None);
    }
    let body = fs::read_to_string(&path)?;
    let title = body
        .lines()
        .find(|line| line.starts_with("# "))
        .map(|line| line.trim_start_matches("# ").trim().to_owned())
        .unwrap_or_else(|| file.trim_end_matches(".md").to_owned());
    let reference = source_ref(CONTROL_WORLD_REF, &format!("{ENGINEERING_GROUND_DIR}/{file}"));
    Ok(Some((title, body, reference)))
}

pub fn render_engineering_ground(central_root: &Path) -> io::Result<String> {
    let mut sections = Vec::new();
    for file in ENGINEERING_GROUND_STATEMENTS {
        if let Some((title, body, reference)) = statement_section(central_root, file)? {
            let revision = content_revision(
                &central_root.join(ENGINEERING_GROUND_DIR).join(file),
            )?;
            sections.push((title, body, reference, revision.revision));
        }
    }
    if sections.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            format!("no engineering statements found under {ENGINEERING_GROUND_DIR}"),
        ));
    }

    let mut out = String::from(
        "# Foundational engineering prompt\n\n\
         <!-- derived source — provenance: generated-derived.\n\
         Do not edit this file; edit the statements under Control/agents/governance/engineering/ \
         and re-run control.engineering-ground.render.\n\
         derived-from:\n",
    );
    for (_, _, reference, revision) in &sections {
        out.push_str(&format!("- {reference} @ {revision}\n"));
    }
    out.push_str(" -->\n\n");
    for (title, body, _, _) in &sections {
        out.push_str(&format!("## {title}\n\n{body}\n\n"));
    }
    Ok(out)
}

pub fn write_engineering_ground(central_root: &Path) -> io::Result<EngineeringGroundRender> {
    let rendered = render_engineering_ground(central_root)?;
    let target = central_root.join(ENGINEERING_GROUND_OUTPUT);
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent)?;
    }
    let changed = match fs::read_to_string(&target) {
        Ok(existing) => existing != rendered,
        Err(error) if error.kind() == io::ErrorKind::NotFound => true,
        Err(error) => return Err(error),
    };
    if changed {
        fs::write(&target, &rendered)?;
    }
    Ok(EngineeringGroundRender {
        output_path: ENGINEERING_GROUND_OUTPUT.to_owned(),
        changed,
        revision: content_revision(&target)?,
    })
}

fn plan_action(_: &ActionRegistry, _: &Value, context: &ActionExecutionContext<'_>) -> ActionResult {
    let action = "control.engineering-ground.plan";
    let root = match resolve_central_root(context.root_options) {
        Ok(root) => root.path,
        Err(message) => {
            return ActionResult::failure(Some(action), ResultStatus::InvalidInput, message, None)
        }
    };
    let outcome = || -> io::Result<serde_json::Value> {
        let rendered = render_engineering_ground(&root)?;
        let target = root.join(ENGINEERING_GROUND_OUTPUT);
        let current = fs::read_to_string(&target).unwrap_or_default();
        Ok(serde_json::json!({
            "output_path": ENGINEERING_GROUND_OUTPUT,
            "would_change": current != rendered,
            "statements": ENGINEERING_GROUND_STATEMENTS.to_vec(),
        }))
    }();
    outcome
        .map(|value| ActionResult::success(action, value))
        .unwrap_or_else(|error| io_failure(action, error))
}

fn render_action(_: &ActionRegistry, _: &Value, context: &ActionExecutionContext<'_>) -> ActionResult {
    let action = "control.engineering-ground.render";
    let root = match resolve_central_root(context.root_options) {
        Ok(root) => root.path,
        Err(message) => {
            return ActionResult::failure(Some(action), ResultStatus::InvalidInput, message, None)
        }
    };
    write_engineering_ground(&root)
        .map(|value| {
            ActionResult::success(action, serde_json::to_value(value).expect("render serializes"))
        })
        .unwrap_or_else(|error| io_failure(action, error))
}

fn io_failure(action: &str, error: io::Error) -> ActionResult {
    let status = match error.kind() {
        io::ErrorKind::InvalidInput | io::ErrorKind::NotFound => ResultStatus::InvalidInput,
        io::ErrorKind::InvalidData => ResultStatus::VerificationFailure,
        _ => ResultStatus::InternalFailure,
    };
    ActionResult::failure(Some(action), status, error.to_string(), None)
}

fn descriptor(id: &str, title: &str, description: &str, mutation_class: MutationClass, output_type: &str) -> ActionDescriptor {
    ActionDescriptor {
        id: id.to_owned(),
        title: title.to_owned(),
        description: description.to_owned(),
        inputs: vec![],
        output: ActionOutputDefinition { output_type: output_type.to_owned() },
        mutation_class,
        preview_supported: mutation_class == MutationClass::ReadOnly,
        required_ports: vec![],
        availability: ActionAvailability { available: true, reason: None },
    }
}

pub fn register_engineering_ground_actions(registry: &mut ActionRegistry) {
    let actions: [(ActionDescriptor, crate::action::ActionHandler); 2] = [
        (
            descriptor(
                "control.engineering-ground.plan",
                "Preview engineering-ground render",
                "Preview whether re-rendering the derived foundational prompt from the Control engineering governance statements would change it, without mutation.",
                MutationClass::ReadOnly,
                "central-engineering-ground-plan",
            ),
            plan_action,
        ),
        (
            descriptor(
                "control.engineering-ground.render",
                "Render engineering-ground prompt",
                "Render the Control engineering governance statements into the derived foundational prompt source (generated-derived; provenance refs pinned). Writes only when content changed; the distillate is machine-derivable and human adoption promotes it.",
                MutationClass::LocallyMutating,
                "central-engineering-ground-render",
            ),
            render_action,
        ),
    ];
    for (descriptor, handler) in actions {
        registry
            .register(descriptor, handler)
            .expect("engineering ground action ids are valid");
    }
}
