use central_ctrl::{
    content_revision, initialize_projectcentral, project_source_bindings,
    render_engineering_ground, write_engineering_ground, ENGINEERING_GROUND_OUTPUT,
    GROUND_RELATIONS_SOURCE,
};
use serde_json::json;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

static NEXT_TEMP_ROOT: AtomicU64 = AtomicU64::new(0);

struct TempRoot(PathBuf);

impl TempRoot {
    fn new(label: &str) -> Self {
        let nonce = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();
        let sequence = NEXT_TEMP_ROOT.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!(
            "central-engineering-ground-{label}-{}-{nonce}-{sequence}",
            std::process::id()
        ));
        fs::create_dir_all(&path).unwrap();
        Self(path)
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TempRoot {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn central_with_statements(name: &str) -> TempRoot {
    let temp = TempRoot::new(name);
    let dir = temp.path().join("Control/agents/governance/engineering");
    fs::create_dir_all(&dir).unwrap();
    for (file, body) in [
        ("agent-operations.md", "You branch small and commit honestly.\n"),
        ("coding-approach.md", "You change the smallest thing that can work.\n"),
        ("verification.md", "You return with evidence of done.\n"),
        ("base-skillset.md", "You reach for the essentials first.\n"),
    ] {
        fs::write(dir.join(file), body).unwrap();
    }
    temp
}

#[test]
fn render_emits_derived_prompt_with_pinned_provenance() {
    let temp = central_with_statements("render");
    let rendered = render_engineering_ground(temp.path()).unwrap();

    assert!(rendered.contains("# Foundational engineering prompt"));
    assert!(rendered.contains("provenance: generated-derived"));
    assert!(rendered.contains(
        "central:source:control:root:Control/agents/governance/engineering/agent-operations.md"
    ));
    // Revision is pinned inline: content-fnv1a64 with the statement's hash.
    let statement = temp.path().join("Control/agents/governance/engineering/agent-operations.md");
    let revision = content_revision(&statement).unwrap();
    assert!(rendered.contains(&revision.revision));
    // Statement bodies are carried verbatim.
    assert!(rendered.contains("You branch small and commit honestly."));
    // The distillate is not human ground and says so.
    assert!(rendered.contains("Do not edit this file"));
    // Render is deterministic.
    assert_eq!(rendered, render_engineering_ground(temp.path()).unwrap());
}

#[test]
fn write_is_cas_stable_and_detects_statement_change() {
    let temp = central_with_statements("write");
    let first = write_engineering_ground(temp.path()).unwrap();
    assert!(first.changed);
    assert_eq!(first.output_path, ENGINEERING_GROUND_OUTPUT);

    let second = write_engineering_ground(temp.path()).unwrap();
    assert!(!second.changed);
    assert_eq!(first.revision, second.revision);

    fs::write(
        temp.path().join("Control/agents/governance/engineering/verification.md"),
        "You return with evidence of done, and say what was not done.\n",
    )
    .unwrap();
    let third = write_engineering_ground(temp.path()).unwrap();
    assert!(third.changed);
    assert_ne!(first.revision, third.revision);
}

#[test]
fn adopted_distillate_participates_as_project_source() {
    let temp = central_with_statements("adopt");
    write_engineering_ground(temp.path()).unwrap();

    let central = temp.path();
    let project = central.join("Work/example-adopt");
    fs::create_dir_all(&project).unwrap();
    initialize_projectcentral(central, &project, "example/adopt").unwrap();

    // Human adoption act: copy the distillate into the project human-source
    // aperture and declare the ground relation.
    let manifest_human_source = "ProjectCentral/user"; // initialise_projectcentral's aperture
    let adopted = project.join(manifest_human_source).join("foundational-prompt.md");
    fs::copy(
        central.join(ENGINEERING_GROUND_OUTPUT),
        &adopted,
    )
    .unwrap();
    fs::create_dir_all(project.join("ProjectCentral/relations")).unwrap();
    fs::write(
        project.join(GROUND_RELATIONS_SOURCE),
        serde_json::to_string_pretty(&json!({
            "schema": "central.project.ground-relations/v1",
            "project_id": "example/adopt",
            "relations": [{
                "ref": "central:source:project:example/adopt:ProjectCentral/user/foundational-prompt.md",
                "path": "ProjectCentral/user/foundational-prompt.md",
                "provenance": "human-adopted",
                "standing": "durable-source",
                "roles": ["project-human-source-aperture"],
                "treatment": "retain-native-in-place"
            }]
        }))
        .unwrap(),
    )
    .unwrap();

    let bindings = project_source_bindings(&project).unwrap();
    let binding = bindings
        .iter()
        .find(|binding| binding.path == "ProjectCentral/user/foundational-prompt.md")
        .expect("adopted distillate participates as a project source");
    assert_eq!(binding.provenance, "human-adopted");
    assert!(binding.agent_retrieval_allowed);
}
